---

- name: Ensure set Rspamd UI password helper script
  ansible.builtin.template:
    src: mailcow_set_rspamd_ui_password.sh.j2
    dest: "{{ mailcow_set_rspamd_ui_password_script }}"
    owner: root
    group: root
    mode: u+x,o-r

- name: Ensure set Rspamd UI password
  ansible.builtin.shell:
    cmd: "{{ mailcow_set_rspamd_ui_password_script }} && touch ansible_done_set_rspamd_ui_password"
  environment:
    _MAILCOW_INSTALL_PATH: "{{ mailcow_install_path }}"
    _MAILCOW_RSPAMD_UI_PASSWORD: "{{ mailcow_rspamd_ui_password }}"
  args:
    creates: ansible_done_set_rspamd_ui_password

...
