---

- name: Ensure greylisting off
  ansible.builtin.blockinfile:
    path: "{{ mailcow_install_path }}data/conf/rspamd/local.d/greylist.conf"
    backup: true
    marker: "### {mark} ANSIBLE MANAGED BLOCK (greylisting off)"
    block: |
      enable = false;
  when: not mailcow_greylisting

...
