---

- name: Get mailcow_version commit
  ansible.builtin.shell:
    chdir: "{{ mailcow_install_path }}"
    cmd: "git rev-list -n 1 {{ mailcow_version }}"
  register: _mailcow_git_rev_list
  changed_when: false

- name: Set fact mailcow_git_commit
  ansible.builtin.set_fact:
    mailcow_git_commit: "{{ _mailcow_git_rev_list.stdout }}"

- name: Ensure mailcow git reset
  ansible.builtin.shell:
    chdir: "{{ mailcow_install_path }}"
    cmd: git reset --hard {{ mailcow_git_commit }} | tee >/root/ansible_done_mailcow_git_reset
    creates: ../ansible_done_mailcow_git_reset

...
