---

- name: Ensure MAILCOW_GIT_VERSION in UI
  ansible.builtin.lineinfile:
    path: "{{ mailcow_install_path }}/data/web/inc/app_info.inc.php"
    regexp: 'MAILCOW_GIT_VERSION'
    line: "  $MAILCOW_GIT_VERSION=\"{{ mailcow_version }}\";"

- name: Get mailcow git commit date
  ansible.builtin.shell:
    chdir: "{{ mailcow_install_path }}"
    cmd: "git show -s --format=%ci {{ mailcow_git_commit }}"
  register: _mailcow_git_commit_date
  changed_when: false

- name: Set fact mailcow_git_commit_date
  ansible.builtin.set_fact:
    mailcow_git_commit_date: "{{ _mailcow_git_commit_date.stdout }}"

- name: Ensure MAILCOW_GIT_COMMIT_DATE in UI
  ansible.builtin.lineinfile:
    path: "{{ mailcow_install_path }}/data/web/inc/app_info.inc.php"
    regexp: 'MAILCOW_GIT_COMMIT_DATE'
    line: "  $MAILCOW_GIT_COMMIT_DATE=\"{{ mailcow_git_commit_date }}\";"

...
