---

- name: Ensure delete default admin helper script
  ansible.builtin.template:
    src:  mailcow_delete_default_admin.sh.j2
    dest: "{{ mailcow_delete_default_admin_script }}"
    owner: root
    group: root
    mode:  u+x,o-r

- name: Ensure set admin helper script
  ansible.builtin.template:
    src:  mailcow_set_admin.sh.j2
    dest: "{{ mailcow_set_admin_script }}"
    owner: root
    group: root
    mode:  u+x,o-r

# - name: Ensure delete default admin
#   ansible.builtin.shell: 
#     cmd: 
#   environment:
#     MAILCOW_ADMIN: admin
#   args:
#     executable: /bin/bash
#     chdir: "{{ mailcow_install_path }}"
#     creates: mailcow.conf

...