---

- name: Ensure oauth2-client in mailcow
  ansible.builtin.uri:
    url: "{{ mailcow_api_url }}/add/oauth2-client"
    body_format: json
    headers:
      X-API-Key: "{{ mailcow_api_key }}"
    method: post
    body:
      redirect_uri:  "{{ mailcow_oauth2_client_redirect_uri }}" # "https://authentik.with.de/source/oauth/callback/mailcow"
      scope:         "{{ mailcow_oauth2_client_scope }}"
  register: _response

...
