---

- name: Ensure set Rspamd UI password helper script
  ansible.builtin.template:
    src:   mailcow_set_rspamd_ui_password.sh.j2
    dest:  "{{ mailcow_set_rspamd_ui_password_script }}"
    owner: root
    group: root
    mode:  u+x,o-r

...