---

- name: Ensure mailcow certbot post-hook script
  ansible.builtin.template:
    src: mailcow_certbot_post-hook.sh.j2
    dest: "{{ mailcow_certbot_post_hook_script }}"
    owner: root
    group: root
    mode: u+x,o-r

- name: Ensure mailcow certbot post-hook script executed
  ansible.builtin.command:
    cmd: "{{ mailcow_certbot_post_hook_script }}"

...
