---

- name: Ensure prepare dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Ensure install mailcow
  ansible.builtin.include_task: mailcow_install.yml
  when: mailcow_install

- name: Ensure mailcow_version
  ansible.builtin.include_tasks: mailcow_version.yml
  when: mailcow_install and (mailcow_version != mailcow_branch)

- name: Ensure mailcow.conf
  ansible.builtin.include_tasks: mailcow_conf.yml
  when: mailcow_configure

- name: Ensure mailcow_version in UI
  ansible.builtin.include_tasks: mailcow_version_ui.yml
  when: mailcow_configure and mailcow_version != mailcow_branch

- name: Ensure mailcow configuration
  ansible.builtin.include_tasks: mailcow_configuration.yml
  when: mailcow_configure

- name: Ensure mailcow is running with docker compose
  ansible.builtin.command:
    cmd:   "docker compose -p {{ mailcow_docker_compose_project_name }} up -d "
    chdir: "{{ mailcow_install_path }}"
  when: mailcow_start

- name: Ensure mailcow admin
  ansible.builtin.include_tasks: mailcow_admin.yml

- name: Ensure mailcow Rspamd UI password
  ansible.builtin.include_tasks: mailcow_rspamd_password.yml

- name: Ensure certbot triggers post-hook script
  ansible.builtin.include_tasks: mailcow_certbot.yml
  when: mailcow_acme == 'certbot'

- name: Ensure mailcow domain
  ansible.builtin.include_tasks: mailcow_domain.yml
  when: mailcow_domain is defined

- name: Ensure mailcow DNS entries
  ansible.builtin.include_tasks: mailcow_dns.yml
  when: mailcow_domain is defined

- name: Ensure configure backup
  ansible.builtin.include_tasks: backup.yml
  when: mailcow_configure_backup

- name: Ensure configure OAUTH2
  ansible.builtin.include_tasks: mailcow_oauth2.yml
  when: mailcow_configure_oauth2

...
