---

- name: Ensure git installed
  ansible.builtin.apt:
    package: git

- name: Ensure mailcow cloned
  ansible.builtin.git:
    repo:    https://github.com/mailcow/mailcow-dockerized.git
    version: "{{ mailcow_version }}"
    update:  no
    dest:    "{{ mailcow_install_path }}"
    umask:   '022'

- name: Ensure mailcow.conf generated
  shell: ./generate_config.sh
  environment:
    MAILCOW_HOSTNAME: "{{ mailcow_hostname }}"
    MAILCOW_TZ: "{{ mailcow_timezone }}"
  args:
    executable: /bin/bash
    chdir: "{{ mailcow_install_path }}"
    creates: mailcow.conf

- name: Ensure software-properties-common is installed
  ansible.builtin.apt:
    name: software-properties-common

- name: Ensure python is installed
  ansible.builtin.apt:
    name: python3

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip

- name: Ensure Python library docker
  ansible.builtin.pip:
    name: docker

- name: Ensure Python library docker-compose
  ansible.builtin.pip:
    name: docker-compose

- name: Ensure mailcow is installed with docker-compose
  community.docker.docker_compose:
    project_name: "{{ mailcow_docker_compose_project_name }}"
    project_src: "{{ mailcow_install_path }}"
    state: "{{ mailcow_docker_compose_state }}"

...