---

- name: Ensure prepare dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Ensure mailcow cloned
  ansible.builtin.git:
    repo:    https://github.com/mailcow/mailcow-dockerized.git
    version: "{{ mailcow_version }}"
    update:  no
    dest:    "{{ mailcow_install_path }}"
    umask:   '022'

- name: Ensure mailcow config
  ansible.builtin.include_tasks: mailcow_config.yml

- name: Ensure mailcow is installed with docker-compose
  community.docker.docker_compose:
    project_name: "{{ mailcow_docker_compose_project_name }}"
    project_src:  "{{ mailcow_install_path }}"
    state:        "{{ mailcow_docker_compose_state }}"

- name: Ensure mailcow admin
  ansible.builtin.include_tasks: mailcow_admin.yml

...