---

- name: Ensure prepare dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Ensure mailcow cloned
  ansible.builtin.git:
    repo: https://github.com/mailcow/mailcow-dockerized.git
    version: "{{ mailcow_version }}"
    update: false
    dest: "{{ mailcow_install_path }}"
    umask: '022'

- name: Ensure mailcow.conf
  ansible.builtin.include_tasks: mailcow_conf.yml

- name: Ensure mailcow is installed with docker-compose
  community.docker.docker_compose:
    project_name: "{{ mailcow_docker_compose_project_name }}"
    project_src: "{{ mailcow_install_path }}"
    state: "{{ mailcow_docker_compose_state }}"

- name: Ensure mailcow admin
  ansible.builtin.include_tasks: mailcow_admin.yml

- name: Ensure mailcow Rspamd UI password
  ansible.builtin.include_tasks: mailcow_rspamd_password.yml

- name: Ensure certbot triggers post-hook script
  ansible.builtin.include_tasks: mailcow_certbot.yml
  when: mailcow_acme == 'certbot'

- name: Ensure mailcow configuration
  ansible.builtin.include_tasks: mailcow_configuration.yml

- name: Ensure mailcow domain
  ansible.builtin.include_tasks: mailcow_domain.yml
  when: lookup('vars', 'mailcow_domain')

- name: Ensure mailcow DNS entries
  ansible.builtin.include_tasks: mailcow_dns.yml

- name: Ensure configure backup
  ansible.builtin.include_tasks: backup.yml
  when: mailcow_configure_backup

...
