---

- name: Ensure prepare dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Ensure mailcow cloned
  ansible.builtin.git:
    repo: https://github.com/mailcow/mailcow-dockerized.git
    version: "{{ mailcow_version }}"
    update: false
    dest: "{{ mailcow_install_path }}"
    umask: '022'

- name: Get mailcow_version commit
  ansible.builtin.shell:
    chdir: "{{ mailcow_install_path }}"
    cmd: "git rev-list -n 1 {{ mailcow_version }}"
  register: _mailcow_git_rev_list
  changed_when: false

- name: Set fact mailcow_git_commit
  ansible.builtin.set_fact:
    mailcow_git_commit: "{{ _mailcow_git_rev_list.stdout }}"

- name: Ensure mailcow git reset
  ansible.builtin.shell:
    chdir: "{{ mailcow_install_path }}"
    cmd: git reset --hard {{ mailcow_git_commit }} | tee >/root/ansible_done_mailcow_git_reset
    creates: ../ansible_done_mailcow_git_reset

- name: Ensure mailcow.conf
  ansible.builtin.include_tasks: mailcow_conf.yml

- name: Ensure mailcow is installed with docker compose
  ansible.builtin.command:
    cmd:   "docker compose -p {{ mailcow_docker_compose_project_name }} up -d "
    chdir: "{{ mailcow_install_path }}"

- name: Ensure mailcow admin
  ansible.builtin.include_tasks: mailcow_admin.yml

- name: Ensure mailcow Rspamd UI password
  ansible.builtin.include_tasks: mailcow_rspamd_password.yml

- name: Ensure certbot triggers post-hook script
  ansible.builtin.include_tasks: mailcow_certbot.yml
  when: mailcow_acme == 'certbot'

- name: Ensure mailcow configuration
  ansible.builtin.include_tasks: mailcow_configuration.yml

- name: Ensure mailcow domain
  ansible.builtin.include_tasks: mailcow_domain.yml
  when: mailcow_domain is defined

- name: Ensure mailcow DNS entries
  ansible.builtin.include_tasks: mailcow_dns.yml
  when: mailcow_domain is defined

- name: Ensure configure backup
  ansible.builtin.include_tasks: backup.yml
  when: mailcow_configure_backup

- name: Ensure configure OAUTH2
  ansible.builtin.include_tasks: mailcow_oauth2.yml
  when: mailcow_configure_oauth2

...
