---

- name: restart rspamd
  ansible.builtin.shell:
    chdir: "{{ mailcow_install_path }}"
    cmd: docker compose restart rspamd-mailcow 

- name: restart postfix
  ansible.builtin.shell:
    chdir: "{{ mailcow_install_path }}"
    cmd: docker compose restart postfix-mailcow 

...